basic.showNumber(123)
basic.showString("GO!")
basic.forever(function () {
    basic.showIcon(IconNames.Heart)
    basic.showIcon(IconNames.SmallHeart)
    basic.showIcon(IconNames.Heart)
    basic.showIcon(IconNames.SmallHeart)
    basic.showString("I ")
    basic.showIcon(IconNames.Heart)
    basic.showString("YOU")
})
